---
- name: nginx install & start service
  hosts: all
  become: true
  tasks:
    - name: install nginx
      yum:
        name: nginx
        state: latest
    - name: start nginx service
      service:
        name: nginx
        state: started
    - name: create web page
      copy:
        src: /root/myassignment/index.html
        dest: /var/www/html/index.html
...
